#!/bin/bash

###  show instructions in the terminal window for how to play inChuck

echo "------------------------------------------------"
echo "Welcome to inChuck. You perform inChuck by adding melodic \"processes\""
echo "to the system, indicating which process, how many times it should be played,"
echo "and in what register.  To add a process to the piece, type:"
echo "   "
echo "chuck + x:y:z"
echo "   "
echo "where:"
echo " x is the process number (1 - 19),"
echo " y is the number of repetions (8 is default), and"
echo " z is the octave (2 - 7, 4 is middle register and default)."
echo "   "
echo "Example: chuck + 3:10:5 plays process #3 ten times an octave above middle C"
echo "   "
echo "Play the processes in sequence. Start at process 1. You are encouraged to "
echo "repeat a process, but you should not go backwards. Focus on one process for"
echo "between 30-60 seconds."
echo "   "
echo "Take your time and listen to what others are doing. Make sure you sustain the"
echo "ensemble's sound density. Most importantly, have fun."
echo "When you have reached process #19 and are done, type \"chuck --kill\"."
echo "   "
echo "If you are the pulse, start now by typing:"
echo "   "
echo "chuck + pulse*"
echo "   "
echo "EMERGENCY: If chuck crashes, or you are unable to proceed, type the following:"
echo "   "
echo "sh restart_inchuck.sh"
echo "   "
echo "This should kill all instances of chuck, and then restart the chuck loop."
echo "------------------------------------------------"
