### Transfer mode - configuration file
#   order of operation
#
#   param   description
#   pre:    local script run before transfer
#   dstdir: remote destination directory
#   sh:     script to be run on remote machines after transfer
#   post:   local script run after transfer

#pre: ~/Desktop/music/piece/scripts/pre_transfer.sh
dstdir: /tmp/
#sh: /tmp/inChuckV3/scripts/decompress_files.sh
#post: ~/Desktop/music/piece/scripts/post_transfer.sh
